# Generated by Django 5.1.2 on 2024-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_number", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=16)),
                ("date_of_birth", models.DateField()),
            ],
        ),
    ]
